<?php

namespace Database\Factories;

use App\Models\Subtitle;
use App\Models\Video;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<Subtitle>
 */
class SubtitleFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $languages = [
            ['code' => 'en', 'name' => 'English'],
            ['code' => 'es', 'name' => 'Spanish'],
            ['code' => 'fr', 'name' => 'French'],
            ['code' => 'de', 'name' => 'German'],
            ['code' => 'it', 'name' => 'Italian'],
            ['code' => 'pt', 'name' => 'Portuguese'],
            ['code' => 'ja', 'name' => 'Japanese'],
            ['code' => 'zh', 'name' => 'Chinese'],
        ];
        $language = $this->faker->randomElement($languages);

        return [
            'video_id' => Video::factory(),
            'language_code' => $language['code'],
            'language_name' => $language['name'],
            'format' => 'vtt',
            'storage_path' => 'subtitles/' . $this->faker->sha1() . '.vtt',
            'file_size_bytes' => $this->faker->numberBetween(50000, 500000),
            'is_auto_generated' => $this->faker->boolean(30),
            'is_verified' => $this->faker->boolean(70),
            'status' => 'completed',
            'line_count' => $this->faker->numberBetween(100, 5000),
        ];
    }

    /**
     * Mark subtitle as auto-generated.
     *
     * @return static
     */
    public function autoGenerated(): static
    {
        return $this->state(fn (array $attributes) => [
            'is_auto_generated' => true,
        ]);
    }

    /**
     * Mark subtitle as unverified.
     *
     * @return static
     */
    public function unverified(): static
    {
        return $this->state(fn (array $attributes) => [
            'is_verified' => false,
        ]);
    }
}
